security:
  oauth2:
    client:
      client-id: clientId
      client-secret: clientSecret
      scope: scope1, scope2, scope3, scope4
      registered-redirect-uri: http://127.0.0.1:8081
server:
  port: 8082